@startuml

'red: #facfd2
'orange: #f7dcc6
'yellow: #f5e6b3
'green: #b8e6bf

skinparam ParticipantPadding 5
skinparam BoxPadding 5
box " " #facfd2
  participant WordPress.com
end box
box "Calypso" #f7dcc6
  participant Undocumented
end box
box "Composite Checkout" #b8e6bf
  participant CompositeCheckout
  participant useShoppingCartManager as "useShopping\nCartManager"
  participant useShoppingCartReducer as "useShopping\nCartReducer"
  participant useCartUpdateAndRevalidate as "useCartUpdate\nAndRevalidate"
end box

'Imports
Undocumented -> CompositeCheckout : import setCart
note over CompositeCheckout
	setCart from props
	or fall back to import
end note
CompositeCheckout -> useShoppingCartManager : setCart
useShoppingCartManager -> useCartUpdateAndRevalidate : setCart
hnote over useShoppingCartReducer
	cacheStatus: 'invalid'
end hnote
useShoppingCartReducer -> useShoppingCartManager : cacheStatus, dispatch
useShoppingCartManager -> useCartUpdateAndRevalidate : cacheStatus, dispatch
note over useCartUpdateAndRevalidate
	cacheStatus === 'invalid'
end note
useCartUpdateAndRevalidate -> Undocumented : << setCart >>
activate Undocumented
Undocumented -> WordPress.com : POST\n/me/shopping-cart/{cartKey}
activate WordPress.com
'Explain renewal flags
note over WordPress.com
	May be passed:

	{ extra: {
		purchaseType: 'renewal'
	} }
end note
return
return
useCartUpdateAndRevalidate -> useShoppingCartReducer : dispatches\nRECEIVE_UPDATED_RESPONSE_CART
note over useShoppingCartReducer
	cacheStatus: 'valid'
end note

@enduml
