@startuml

'red: #facfd2
'orange: #f7dcc6
'yellow: #f5e6b3
'green: #b8e6bf

skinparam ParticipantPadding 5
skinparam BoxPadding 5

box "Actions" #f5e6b3
	control SecondaryCartPromotions as "SecondaryCart\nPromotions"
	control UpcomingRenewalsReminder as "Upcoming\nRenewalsReminder"
	control CartFreeUserPlanUpsell as "CartFreeUser\nPlanUpsell"
end box
box "Composite Checkout" #b8e6bf
  participant CompositeCheckout
  participant useShoppingCartManager as "useShopping\nCartManager"
  participant useShoppingCartReducer as "useShopping\nCartReducer"
end box

'Props
useShoppingCartManager -> CompositeCheckout : addProductsToCart
CompositeCheckout -> SecondaryCartPromotions : addProductsToCart
SecondaryCartPromotions -> UpcomingRenewalsReminder : addProductsToCart
note over UpcomingRenewalsReminder
	<< getRenewableSitePurchases >>
	sent to
	<< getRenewalItemFromProduct >>
		<< getRenewalItemFromCartItem >>
end note
UpcomingRenewalsReminder -> useShoppingCartManager : << addProductsToCart >>
SecondaryCartPromotions -> CartFreeUserPlanUpsell : addProductsToCart
note over CartFreeUserPlanUpsell
	<< planItem >>
end note
CartFreeUserPlanUpsell -> useShoppingCartManager : << addProductsToCart >>
useShoppingCartManager -> useShoppingCartReducer : dispatches\nCART_PRODUCTS_ADD

'Cache invalidation
note over useShoppingCartReducer
	cacheStatus: 'invalid'
end note

@enduml
